import type { TimeWindow } from "./time";
import { sampleByUnit } from "./time";

/**
 * Pure SQL builders for QuestDB's HTTP `/exec` endpoint.
 *
 * Every builder returns a string and performs no I/O, so they are exhaustively
 * unit-tested. Identifiers are fixed (no user-supplied column names); the only
 * interpolated values are timestamps (ISO, generated by us) and the device id,
 * which is escaped.
 */

export function escapeLiteral(value: string): string {
  return value.replace(/'/g, "''");
}

/** Build a WHERE clause from optional predicates. */
function where(predicates: Array<string | null | undefined>): string {
  const parts = predicates.filter((p): p is string => Boolean(p));
  return parts.length ? `WHERE ${parts.join(" AND ")}` : "";
}

function deviceEq(deviceId: string | null): string | null {
  return deviceId ? `device_id = '${escapeLiteral(deviceId)}'` : null;
}

function timeRange(window: Pick<TimeWindow, "from" | "to">): string {
  return `ts >= '${window.from}' AND ts < '${window.to}'`;
}

/** The most recently seen device id (used when none is configured). */
export function latestDeviceSql(): string {
  return "SELECT device_id FROM power_flows LATEST ON ts PARTITION BY device_id";
}

/** Latest instantaneous power-flow reading. */
export function latestFlowSql(deviceId: string | null): string {
  const w = where([deviceEq(deviceId)]);
  return `SELECT ts, site, grid, pv, battery FROM power_flows ${w} LATEST ON ts PARTITION BY device_id`.trim();
}

/** Latest battery state. */
export function latestBatterySql(deviceId: string | null): string {
  const w = where([deviceEq(deviceId)]);
  return `SELECT ts, soc, soe, grid_state, connected FROM panel_bess ${w} LATEST ON ts PARTITION BY device_id`.trim();
}

/** Latest state of every circuit, ordered by current draw (descending). */
export function circuitsLatestSql(deviceId: string | null): string {
  const w = where([deviceEq(deviceId)]);
  const inner =
    `SELECT circuit_id, name, active_power, relay, space, breaker_rating, sheddable, always_on ` +
    `FROM circuits ${w} LATEST ON ts PARTITION BY circuit_id`.trim();
  // active_power is negative for consumption, so ascending puts the biggest
  // consumers first.
  return `SELECT * FROM (${inner}) ORDER BY active_power ASC`;
}

/**
 * Source power series, bucketed and timezone-aligned.
 *
 * Returns, per bucket: average watts for each source plus the charge/discharge
 * split for the battery and the sample count, so the transform can integrate
 * average power into energy (kWh).
 */
export function flowSeriesSql(
  window: TimeWindow,
  tz: string,
  deviceId: string | null,
): string {
  const w = where([deviceEq(deviceId), timeRange(window)]);
  const unit = sampleByUnit(window.bucket);
  return (
    `SELECT ts, ` +
    `avg(site) site_w, avg(pv) pv_w, avg(grid) grid_w, avg(battery) battery_w, ` +
    `sum(CASE WHEN battery > 0 THEN battery ELSE 0 END) batt_charge_sum, ` +
    `sum(CASE WHEN battery < 0 THEN -battery ELSE 0 END) batt_discharge_sum, ` +
    `sum(CASE WHEN grid < 0 THEN -grid ELSE 0 END) grid_import_sum, ` +
    `sum(CASE WHEN grid > 0 THEN grid ELSE 0 END) grid_export_sum, ` +
    `count() n ` +
    `FROM power_flows ${w} ` +
    `SAMPLE BY ${unit} FILL(NULL) ALIGN TO CALENDAR TIME ZONE '${escapeLiteral(tz)}'`
  );
}

/** Battery state-of-charge series for the same window. */
export function socSeriesSql(
  window: TimeWindow,
  tz: string,
  deviceId: string | null,
): string {
  const w = where([deviceEq(deviceId), timeRange(window)]);
  const unit = sampleByUnit(window.bucket);
  return (
    `SELECT ts, avg(soc) soc FROM panel_bess ${w} ` +
    `SAMPLE BY ${unit} FILL(LINEAR) ALIGN TO CALENDAR TIME ZONE '${escapeLiteral(tz)}'`
  );
}

/** Per-circuit energy consumed over the window (Wh summed → caller converts). */
export function circuitEnergySql(
  window: TimeWindow,
  deviceId: string | null,
): string {
  const w = where([deviceEq(deviceId), timeRange(window), "node_type = 'circuit'"]);
  return (
    // A circuit's consumption energy is in exported_wh (delivered to the load).
    `SELECT node_id, name, sum(imported_wh) imported_wh, sum(exported_wh) exported_wh ` +
    `FROM power_usage ${w} GROUP BY node_id, name ORDER BY exported_wh DESC`
  );
}

/**
 * Window-total source energy via average power.
 * One row of average watts per source over the whole window.
 */
export function flowTotalsSql(
  window: Pick<TimeWindow, "from" | "to">,
  deviceId: string | null,
): string {
  const w = where([deviceEq(deviceId), timeRange(window)]);
  return (
    `SELECT avg(site) site_w, avg(pv) pv_w, avg(grid) grid_w, avg(battery) battery_w, ` +
    `sum(CASE WHEN battery > 0 THEN battery ELSE 0 END) batt_charge_sum, ` +
    `sum(CASE WHEN battery < 0 THEN -battery ELSE 0 END) batt_discharge_sum, ` +
    `sum(CASE WHEN grid < 0 THEN -grid ELSE 0 END) grid_import_sum, ` +
    `sum(CASE WHEN grid > 0 THEN grid ELSE 0 END) grid_export_sum, ` +
    `count() n FROM power_flows ${w}`
  );
}
