import type { TimeWindow } from "./time";
import { sampleByUnit } from "./time";

/**
 * Pure SQL builders for QuestDB's HTTP `/exec` endpoint.
 *
 * Every builder returns a string and performs no I/O, so they are exhaustively
 * unit-tested. Identifiers are fixed (no user-supplied column names); the only
 * interpolated values are timestamps (ISO, generated by us) and the device id,
 * which is escaped.
 */

export function escapeLiteral(value: string): string {
  return value.replace(/'/g, "''");
}

/** Build a WHERE clause from optional predicates. */
function where(predicates: Array<string | null | undefined>): string {
  const parts = predicates.filter((p): p is string => Boolean(p));
  return parts.length ? `WHERE ${parts.join(" AND ")}` : "";
}

function deviceEq(deviceId: string | null): string | null {
  return deviceId ? `device_id = '${escapeLiteral(deviceId)}'` : null;
}

function timeRange(window: Pick<TimeWindow, "from" | "to">): string {
  return `ts >= '${window.from}' AND ts < '${window.to}'`;
}

/**
 * Hourly rollup of power_flows, maintained by QuestDB as a materialized view
 * (see the collector's viewDDL). Long-range queries read this instead of the
 * raw table — thousands of pre-aggregated rows vs tens of millions.
 */
const FLOW_ROLLUP_VIEW = "power_flows_1h";

/**
 * The rollup is used only for windows strictly longer than this. 26h keeps every
 * "today" variant (23–25h across DST) on the raw path, while week/month/year go
 * to the rollup.
 */
const ROLLUP_MIN_WINDOW_MS = 26 * 60 * 60 * 1000;

/**
 * Whether to read the hourly rollup rather than the raw table. Long windows use
 * it; shorter ones (today / sub-day custom) stay on raw for full resolution and
 * zero rollup-refresh lag. Called once per API request (not a hot path), so the
 * two Date parses are negligible next to the QuestDB round-trip that follows.
 */
function usesRollup(window: Pick<TimeWindow, "from" | "to">): boolean {
  return new Date(window.to).getTime() - new Date(window.from).getTime() > ROLLUP_MIN_WINDOW_MS;
}

/**
 * The flow aggregate projection (everything after the optional `ts`), shared by
 * the series and totals builders so the two never drift. Two forms:
 *   - RAW: computed from raw power_flows rows.
 *   - ROLLUP: re-aggregated from the hourly rollup — count-weighted averages
 *     (`sum(avg*n)/sum(n)` == the raw average, exactly) + additive sums.
 * The collector's view definition (viewDDL, in Go) necessarily mirrors the raw
 * form across the language boundary.
 */
const RAW_FLOW_PROJECTION =
  `avg(site) site_w, avg(pv) pv_w, avg(grid) grid_w, avg(battery) battery_w, ` +
  `sum(CASE WHEN battery > 0 THEN battery ELSE 0 END) batt_charge_sum, ` +
  `sum(CASE WHEN battery < 0 THEN -battery ELSE 0 END) batt_discharge_sum, ` +
  `sum(CASE WHEN grid < 0 THEN -grid ELSE 0 END) grid_import_sum, ` +
  `sum(CASE WHEN grid > 0 THEN grid ELSE 0 END) grid_export_sum, ` +
  `count() n`;

const ROLLUP_FLOW_PROJECTION =
  `sum(site_w * n) / sum(n) site_w, sum(pv_w * n) / sum(n) pv_w, ` +
  `sum(grid_w * n) / sum(n) grid_w, sum(battery_w * n) / sum(n) battery_w, ` +
  `sum(batt_charge_sum) batt_charge_sum, sum(batt_discharge_sum) batt_discharge_sum, ` +
  `sum(grid_import_sum) grid_import_sum, sum(grid_export_sum) grid_export_sum, ` +
  `sum(n) n`;

/** The most recently seen device id (used when none is configured). */
export function latestDeviceSql(): string {
  return "SELECT device_id FROM power_flows LATEST ON ts PARTITION BY device_id";
}

/**
 * Tables the collector writes on every cycle. If any of these has a stale
 * `max(ts)`, ingestion (or that specific table) has stalled — a single-table
 * check would miss a per-table failure like the circuits outage. `panel_bess`
 * is deliberately excluded: it updates only every few minutes and would
 * false-trip a one-minute staleness check.
 */
export const FRESHNESS_TABLES = [
  "power_usage",
  "circuits",
  "power_flows",
  "panel_core",
  "panel_lugs",
] as const;

/** One of the fixed sentinel table names. */
export type FreshnessTable = (typeof FRESHNESS_TABLES)[number];

/**
 * Latest write time per sentinel table — one row each: `tbl`, `ts`.
 *
 * `tables` is typed to the `FreshnessTable` union, not `string`, so only the
 * known sentinel identifiers can ever be interpolated — there is no path for
 * caller-supplied text to reach the query (no injection surface).
 */
export function freshnessSql(tables: readonly FreshnessTable[] = FRESHNESS_TABLES): string {
  return tables.map((t) => `SELECT '${t}' tbl, max(ts) ts FROM ${t}`).join(" UNION ALL ");
}

/** Latest instantaneous power-flow reading. */
export function latestFlowSql(deviceId: string | null): string {
  const w = where([deviceEq(deviceId)]);
  return `SELECT ts, site, grid, pv, battery FROM power_flows ${w} LATEST ON ts PARTITION BY device_id`.trim();
}

/** Latest battery state. */
export function latestBatterySql(deviceId: string | null): string {
  const w = where([deviceEq(deviceId)]);
  return `SELECT ts, soc, soe, grid_state, connected FROM panel_bess ${w} LATEST ON ts PARTITION BY device_id`.trim();
}

/** Latest state of every circuit, ordered by current draw (descending). */
export function circuitsLatestSql(deviceId: string | null): string {
  const w = where([deviceEq(deviceId)]);
  const inner =
    `SELECT circuit_id, name, active_power, relay, space, breaker_rating, sheddable, always_on ` +
    `FROM circuits ${w} LATEST ON ts PARTITION BY circuit_id`.trim();
  // active_power is negative for consumption, so ascending puts the biggest
  // consumers first.
  return `SELECT * FROM (${inner}) ORDER BY active_power ASC`;
}

/**
 * Source power series, bucketed and timezone-aligned.
 *
 * Returns, per bucket: average watts for each source plus the charge/discharge
 * split for the battery and the sample count, so the transform can integrate
 * average power into energy (kWh).
 */
export function flowSeriesSql(
  window: TimeWindow,
  tz: string,
  deviceId: string | null,
): string {
  const w = where([deviceEq(deviceId), timeRange(window)]);
  const unit = sampleByUnit(window.bucket);
  const tail = `${w} SAMPLE BY ${unit} FILL(NULL) ALIGN TO CALENDAR TIME ZONE '${escapeLiteral(tz)}'`;
  return usesRollup(window)
    ? `SELECT ts, ${ROLLUP_FLOW_PROJECTION} FROM ${FLOW_ROLLUP_VIEW} ${tail}`
    : `SELECT ts, ${RAW_FLOW_PROJECTION} FROM power_flows ${tail}`;
}

/** Battery state-of-charge series for the same window. */
export function socSeriesSql(
  window: TimeWindow,
  tz: string,
  deviceId: string | null,
): string {
  const w = where([deviceEq(deviceId), timeRange(window)]);
  const unit = sampleByUnit(window.bucket);
  return (
    `SELECT ts, avg(soc) soc, avg(soe) soe FROM panel_bess ${w} ` +
    `SAMPLE BY ${unit} FILL(LINEAR) ALIGN TO CALENDAR TIME ZONE '${escapeLiteral(tz)}'`
  );
}

/** Per-circuit energy consumed over the window (Wh summed → caller converts). */
export function circuitEnergySql(
  window: TimeWindow,
  deviceId: string | null,
): string {
  const w = where([deviceEq(deviceId), timeRange(window), "node_type = 'circuit'"]);
  return (
    // A circuit's consumption energy is in exported_wh (delivered to the load).
    `SELECT node_id, name, sum(imported_wh) imported_wh, sum(exported_wh) exported_wh ` +
    `FROM power_usage ${w} GROUP BY node_id, name ORDER BY exported_wh DESC`
  );
}

/**
 * Window-total source energy via average power.
 * One row of average watts per source over the whole window.
 */
export function flowTotalsSql(
  window: Pick<TimeWindow, "from" | "to">,
  deviceId: string | null,
): string {
  const w = where([deviceEq(deviceId), timeRange(window)]);
  return usesRollup(window)
    ? `SELECT ${ROLLUP_FLOW_PROJECTION} FROM ${FLOW_ROLLUP_VIEW} ${w}`
    : `SELECT ${RAW_FLOW_PROJECTION} FROM power_flows ${w}`;
}

/**
 * Per-bucket consumption energy (Wh summed) for a single circuit, timezone
 * aligned. exported_wh is the energy delivered to the circuit (its consumption).
 */
export function circuitSeriesSql(
  circuitId: string,
  window: TimeWindow,
  tz: string,
  deviceId: string | null,
): string {
  const w = where([
    deviceEq(deviceId),
    `node_id = '${escapeLiteral(circuitId)}'`,
    "node_type = 'circuit'",
    timeRange(window),
  ]);
  const unit = sampleByUnit(window.bucket);
  return (
    `SELECT ts, sum(exported_wh) wh FROM power_usage ${w} ` +
    `SAMPLE BY ${unit} FILL(0) ALIGN TO CALENDAR TIME ZONE '${escapeLiteral(tz)}'`
  );
}
